my_dict = {
    0: 'Chihuahua',
    1: 'Japanese spaniel',
    2: 'Maltese dog',
    3: 'Pekinese',
    4: 'Shih-Tzu',
    5: 'Blenheim spaniel',
    6: 'papillon',
    7: 'toy terrier',
    8: 'Rhodesian ridgeback',
    9: 'Afghan hound',
    10: 'basset',
    11: 'beagle',
    12: 'bloodhound',
    13: 'bluetick',
    14: 'black-and-tan coonhound',
    15: 'Walker hound',
    16: 'English foxhound',
    17: 'redbone',
    18: 'borzoi',
    19: 'Irish wolfhound',
    20: 'Italian greyhound',
    21: 'whippet',
    22: 'Ibizan hound',
    23: 'Norwegian elkhound',
    24: 'otterhound',
    25: 'Saluki',
    26: 'Scottish deerhound',
    27: 'Weimaraner',
    28: 'Staffordshire bullterrier',
    29: 'American Staffordshire terrier',
    30: 'Bedlington terrier',
    31: 'Border terrier',
    32: 'Kerry blue terrier',
    33: 'Irish terrier',
    34: 'Norfolk terrier',
    35: 'Norwich terrier',
    36: 'Yorkshire terrier',
    37: 'wire-haired fox terrier',
    38: 'Lakeland terrier',
    39: 'Sealyham terrier',
    40: 'Airedale',
    41: 'cairn',
    42: 'Australian terrier',
    43: 'Dandie Dinmont',
    44: 'Boston bull',
    45: 'miniature schnauzer',
    46: 'giant schnauzer',
    47: 'standard schnauzer',
    48: 'Scotch terrier',
    49: 'Tibetan terrier',
    50: 'silky terrier',
    51: 'soft-coated wheaten terrier',
    52: 'West Highland white terrier',
    53: 'Lhasa',
    54: 'flat-coated retriever',
    55: 'curly-coated retriever',
    56: 'golden retriever',
    57: 'Labrador retriever',
    58: 'Chesapeake Bay retriever',
    59: 'German short-haired pointer',
    60: 'vizsla',
    61: 'English setter',
    62: 'Irish setter',
    63: 'Gordon setter',
    64: 'Brittany spaniel',
    65: 'clumber',
    66: 'English springer',
    67: 'Welsh springer spaniel',
    68: 'cocker spaniel',
    69: 'Sussex spaniel',
    70: 'Irish water spaniel',
    71: 'kuvasz',
    72: 'schipperke',
    73: 'groenendael',
    74: 'malinois',
    75: 'briard',
    76: 'kelpie',
    77: 'komondor',
    78: 'Old English sheepdog',
    79: 'Shetland sheepdog',
    80: 'collie',
    81: 'Border collie',
    82: 'Bouvier des Flandres',
    83: 'Rottweiler',
    84: 'German shepherd',
    85: 'Doberman',
    86: 'miniature pinscher',
    87: 'Greater Swiss Mountain dog',
    88: 'Bernese mountain dog',
    89: 'Appenzeller',
    90: 'EntleBucher',
    91: 'boxer',
    92: 'bull mastiff',
    93: 'Tibetan mastiff',
    94: 'French bulldog',
    95: 'Great Dane',
    96: 'Saint Bernard',
    97: 'Eskimo dog',
    98: 'malamute',
    99: 'Siberian husky',
    100: 'affenpinscher',
    101: 'basenji',
    102: 'pug',
    103: 'Leonberg',
    104: 'Newfoundland',
    105: 'Great Pyrenees',
    106: 'Samoyed',
    107: 'Pomeranian',
    108: 'chow',
    109: 'keeshond',
    110: 'Brabancon griffon',
    111: 'Pembroke',
    112: 'Cardigan',
    113: 'toy poodle',
    114: 'miniature poodle',
    115: 'standard poodle',
    116: 'Mexican hairless',
    117: 'dingo',
    118: 'dhole',
    119: 'African hunting dog',
}
