name: Image Finetune Training
id: 034d29ec-d74e-4f3a-96eb-33365e53e77b
category: Machine Learning\Train
description: Creates a DenseNet for image classification and trains it
inputs:
- name: Data path
  type: GenericFolder
  port: True
  description: data_path
- name: Model Type
  type: Mode
  default: 'densenet201'
  description: model_type
  options:
    - 'densenet201'
    - 'densenet169'
    - 'densenet161'
    - 'densenet121'
- name: Pretrained
  type: Boolean
  default: True
  description: pretrained
- name: Memory efficient
  type: Boolean
  default: False
  description: memory_efficient
- name: Epochs
  type: Int
  default: 1
  description: epochs
- name: Batch size
  type: Int
  default: 4
  description: batch_size
- name: Random seed
  type: Int
  default: 1
  description: random_seed
outputs:
- name: Save path
  type: ModelFolder
  description: save_path
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.3
      - pip:
        - fire==0.1.3
        - scipy==1.2.1
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
        - git+https://github.com/zyh911/azureml-custom-module-examples.git@master#subdirectory=image-classification-densenet-imagenet
    command:
    - python
    - -m
    - script.train
    args:
    - --data_path
    - inputValue: Data path
    - --model_type
    - inputValue: Model Type
    - --pretrained
    - inputValue: Pretrained
    - --memory_efficient
    - inputValue: Memory efficient
    - --epochs
    - inputValue: Epochs
    - --batch_size
    - inputValue: Batch size
    - --random_seed
    - inputValue: Random seed
    - --save_path
    - outputPath: Save path
